spring:
  main:
    banner-mode: off
  application:
    name: assembly
  data:
    mongodb:
      uri: mongodb://root:root@localhost/admin
      auto-index-creation: true
integration:
  cpf: https://user-info.herokuapp.com


